/* This file was generated by Grammax v1.1.1 */

#ifndef GRAMMAX_PARSER_PARSER_H
#define GRAMMAX_PARSER_PARSER_H
#include <vector>
#include <cstring> // for std::memcpy

#include "ast.hpp"
#include "token.hpp"

class Parser {
private:
#define T_WORD_CHARS 0
#define T_OR 1
#define T_RIGHT_PARENTHESIS 2
#define T_LEFT_BRACKET 3
#define T_NON_DIGIT_CHARS 4
#define T_NON_WHITESPACE_CHARS 5
#define T_DOT 6
#define T_UP_ARROW 7
#define T_SPECIAL_CHARACTER 8
#define T_LEFT_PARENTHESIS_QUESTION_MARK_COLON 9
#define T_MINUS 10
#define T_DIGIT_CHARS 11
#define T_RIGHT_BRACKET 12
#define T_LEFT_PARENTHESIS 13
#define T_NON_WORD_CHARS 14
#define T_WHITESPACE_CHARS 15
#define T_QUESTION_MARK 16
#define T_STAR 17
#define T_CHARACTER 18
#define T_PLUS 19
#define T_EOF 20
#define TERMINAL_COUNT 21
#define NON_TERMINAL_COUNT 12
    static constexpr int gotoTable[] = {
        4,12,9,14,0,2,17,0,10,0,0,6,
        0,0,0,0,22,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,12,9,27,0,2,17,0,0,0,0,6,
        28,12,9,14,0,2,17,0,10,0,0,6,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        29,12,9,14,0,2,17,0,10,0,0,6,
        0,37,0,0,0,0,0,45,0,42,39,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,12,9,14,0,2,17,0,46,0,0,6,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,37,0,0,0,0,0,45,0,42,50,0,
        0,37,0,0,0,0,0,45,0,42,52,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,55,0,0,0,0,0,45,0,56,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,12,9,27,0,2,17,0,0,0,0,6,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,55,0,0,0,0,0,45,0,56,0,0,
        0,37,0,0,0,0,0,45,0,42,60,0,
        0,55,0,0,0,0,0,45,0,56,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,62,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,55,0,0,0,0,0,45,0,56,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,0,0,0,0};
    static constexpr int actionTable[] = {
        7,-5,-5,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-5,
        -11,-11,-11,-11,-11,-11,-11,0,-11,-11,0,-11,0,-11,-11,-11,25,24,-11,23,-11,
        -15,-15,-15,-15,-15,-15,-15,0,-15,-15,0,-15,0,-15,-15,-15,-15,-15,-15,-15,-15,
        0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,
        -23,-23,-23,-23,-23,-23,-23,-23,-23,-23,0,-23,-23,-23,-23,-23,-23,-23,-23,-23,-23,
        -19,-19,-19,-19,-19,-19,-19,0,-19,-19,0,-19,0,-19,-19,-19,-19,-19,-19,-19,-19,
        -20,-20,-20,-20,-20,-20,-20,-20,-20,-20,0,-20,-20,-20,-20,-20,-20,-20,-20,-20,-20,
        -25,-25,-25,-25,-25,-25,-25,-25,-25,-25,0,-25,-25,-25,-25,-25,-25,-25,-25,-25,-25,
        -17,-17,-17,-17,-17,-17,-17,0,-17,-17,0,-17,0,-17,-17,-17,-17,-17,-17,-17,-17,
        7,-4,-4,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-4,
        7,-5,-5,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-5,
        -16,-16,-16,-16,-16,-16,-16,0,-16,-16,0,-16,0,-16,-16,-16,-16,-16,-16,-16,-16,
        -50,-50,-50,-50,-50,-50,-50,0,-50,-50,0,-50,0,-50,-50,-50,-50,-50,-50,-50,-50,
        -7,-7,-7,-7,-7,-7,-7,0,-7,-7,0,-7,0,-7,-7,-7,0,0,-7,0,-7,
        -21,-21,-21,-21,-21,-21,-21,-21,-21,-21,0,-21,-21,-21,-21,-21,-21,-21,-21,-21,-21,
        -22,-22,-22,-22,-22,-22,-22,-22,-22,-22,0,-22,-22,-22,-22,-22,-22,-22,-22,-22,-22,
        -18,-18,-18,-18,-18,-18,-18,0,-18,-18,0,-18,0,-18,-18,-18,-18,-18,-18,-18,-18,
        7,-5,-5,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-5,
        7,31,30,43,5,8,32,35,38,0,0,16,34,36,15,20,33,41,44,40,0,
        -24,-24,-24,-24,-24,-24,-24,-24,-24,-24,0,-24,-24,-24,-24,-24,-24,-24,-24,-24,-24,
        -49,-49,-49,-49,-49,-49,-49,0,-49,-49,0,-49,0,-49,-49,-49,-49,-49,-49,-49,-49,
        -10,-10,-10,-10,-10,-10,-10,0,-10,-10,0,-10,0,-10,-10,-10,0,0,-10,0,-10,
        -13,-13,-13,-13,-13,-13,-13,0,-13,-13,0,-13,0,-13,-13,-13,0,0,-13,0,-13,
        -12,-12,-12,-12,-12,-12,-12,0,-12,-12,0,-12,0,-12,-12,-12,0,0,-12,0,-12,
        -14,-14,-14,-14,-14,-14,-14,0,-14,-14,0,-14,0,-14,-14,-14,0,0,-14,0,-14,
        7,-3,-3,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-3,
        -6,-6,-6,-6,-6,-6,-6,0,-6,-6,0,-6,0,-6,-6,-6,0,0,-6,0,-6,
        0,26,47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        0,26,48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
        -46,-46,-46,-46,-46,-46,-46,-46,-46,0,-46,-46,-46,-46,-46,-46,-46,-46,-46,-46,0,
        -41,-41,-41,-41,-41,-41,-41,-41,-41,0,-41,-41,-41,-41,-41,-41,-41,-41,-41,-41,0,
        -43,-43,-43,-43,-43,-43,-43,-43,-43,0,-43,-43,-43,-43,-43,-43,-43,-43,-43,-43,0,
        -47,-47,-47,-47,-47,-47,-47,-47,-47,0,-47,-47,-47,-47,-47,-47,-47,-47,-47,-47,0,
        7,31,30,43,5,8,32,0,38,0,0,16,49,36,15,20,33,41,44,40,0,
        7,31,30,43,5,8,32,0,38,0,0,16,51,36,15,20,33,41,44,40,0,
        -45,-45,-45,-45,-45,-45,-45,-45,-45,0,-45,-45,-45,-45,-45,-45,-45,-45,-45,-45,0,
        -36,-36,-36,-36,-36,-36,-36,-36,-36,0,0,-36,-36,-36,-36,-36,-36,-36,-36,-36,0,
        -40,-40,-40,-40,-40,-40,-40,-40,-40,0,-40,-40,-40,-40,-40,-40,-40,-40,-40,-40,0,
        7,31,30,43,5,8,32,54,38,0,0,16,53,36,15,20,33,41,44,40,0,
        -44,-44,-44,-44,-44,-44,-44,-44,-44,0,-44,-44,-44,-44,-44,-44,-44,-44,-44,-44,0,
        -48,-48,-48,-48,-48,-48,-48,-48,-48,0,-48,-48,-48,-48,-48,-48,-48,-48,-48,-48,0,
        -34,-34,-34,-34,-34,-34,-34,-34,-34,0,0,-34,-34,-34,-34,-34,-34,-34,-34,-34,0,
        -42,-42,-42,-42,-42,-42,-42,-42,-42,0,-42,-42,-42,-42,-42,-42,-42,-42,-42,-42,0,
        -39,-39,-39,-39,-39,-39,-39,-39,-39,0,-39,-39,-39,-39,-39,-39,-39,-39,-39,-39,0,
        -38,-38,-38,-38,-38,-38,-38,-38,-38,0,57,-38,-38,-38,-38,-38,-38,-38,-38,-38,0,
        7,-2,-2,19,5,8,3,0,13,18,0,16,0,11,15,20,0,0,21,0,-2,
        -8,-8,-8,-8,-8,-8,-8,0,-8,-8,0,-8,0,-8,-8,-8,-8,-8,-8,-8,-8,
        -9,-9,-9,-9,-9,-9,-9,0,-9,-9,0,-9,0,-9,-9,-9,-9,-9,-9,-9,-9,
        -30,-30,-30,-30,-30,-30,-30,0,-30,-30,0,-30,0,-30,-30,-30,-30,-30,-30,-30,-30,
        7,31,30,43,5,8,32,54,38,0,0,16,58,36,15,20,33,41,44,40,0,
        7,31,30,43,5,8,32,0,38,0,0,16,59,36,15,20,33,41,44,40,0,
        7,31,30,43,5,8,32,54,38,0,0,16,61,36,15,20,33,41,44,40,0,
        -26,-26,-26,-26,-26,-26,-26,0,-26,-26,0,-26,0,-26,-26,-26,-26,-26,-26,-26,-26,
        -33,-33,-33,-33,-33,-33,-33,-33,-33,0,0,-33,-33,-33,-33,-33,-33,-33,-33,-33,0,
        -35,-35,-35,-35,-35,-35,-35,-35,-35,0,0,-35,-35,-35,-35,-35,-35,-35,-35,-35,0,
        -32,-32,-32,-32,-32,-32,-32,-32,-32,0,0,-32,-32,-32,-32,-32,-32,-32,-32,-32,0,
        0,31,30,43,0,0,32,0,38,0,0,0,0,36,0,0,33,41,44,40,0,
        -28,-28,-28,-28,-28,-28,-28,0,-28,-28,0,-28,0,-28,-28,-28,-28,-28,-28,-28,-28,
        -31,-31,-31,-31,-31,-31,-31,0,-31,-31,0,-31,0,-31,-31,-31,-31,-31,-31,-31,-31,
        7,31,30,43,5,8,32,54,38,0,0,16,63,36,15,20,33,41,44,40,0,
        -27,-27,-27,-27,-27,-27,-27,0,-27,-27,0,-27,0,-27,-27,-27,-27,-27,-27,-27,-27,
        -37,-37,-37,-37,-37,-37,-37,-37,-37,0,0,-37,-37,-37,-37,-37,-37,-37,-37,-37,0,
        -29,-29,-29,-29,-29,-29,-29,0,-29,-29,0,-29,0,-29,-29,-29,-29,-29,-29,-29,-29};
    static constexpr int productionLabels[] = {0,0,0,0,8,8,11,11,3,3,4,4,4,5,5,5,5,5,1,1,1,1,1,1,2,2,2,2,2,2,10,10,10,10,10,9,9,7,7,7,7,7,7,7,7,7,7,6,6};
public:
    union StackEntryPayload {
        void* _grx_object;
        Expression* expression;
        CharacterClass character_class;
        CharacterAlt* character_alt;
        Match* match;
        char SPECIAL_CHARACTER;
        Quantifier quantifier;
        MatchElement* match_elem;
        char character_set_char;
        char literal;
        Conjunction* conjunction;
        CharacterRange* character_range;
        CharacterSet* character_set;
        char CHARACTER;
        Group* group;

        StackEntryPayload() {}
        ~StackEntryPayload() {}
        StackEntryPayload(StackEntryPayload&& other) noexcept {
            std::memcpy(this, &other, sizeof(StackEntryPayload));
        }
        StackEntryPayload(const StackEntryPayload& other) noexcept {
            std::memcpy(this, &other, sizeof(StackEntryPayload));
        }
        StackEntryPayload& operator=(StackEntryPayload&& other) noexcept {
            if (this != &other) {
                std::memcpy(this, &other, sizeof(StackEntryPayload));
            }
            return *this;
        }
        StackEntryPayload& operator=(const StackEntryPayload& other) {
            if (this != &other) {
                std::memcpy(this, &other, sizeof(StackEntryPayload));
            }
            return *this;
        }
    };
private:
    struct StackEntry {
        int previousState;
        StackEntryPayload payload;
        StackEntry(int previousState, StackEntryPayload payload) : previousState(previousState), payload(std::move(payload)) {}
        StackEntry() : previousState(0) {
            payload._grx_object = nullptr;
        }
        StackEntry(StackEntry&&) = default;
    };
    static StackEntryPayload _reduction0(std::vector<StackEntry>* _grx_stack) {
        Conjunction* C = _grx_stack->back().payload.conjunction;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        Expression* E = _grx_stack->back().payload.expression;
        _grx_stack->pop_back();
        Expression* v;
        {
         v = E; v->add_child(C); 
        }
        StackEntryPayload _grx_v;
        _grx_v.expression = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction1(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Expression* E = _grx_stack->back().payload.expression;
        _grx_stack->pop_back();
        Expression* v;
        {
         v = E; v->add_child(new Conjunction()); 
        }
        StackEntryPayload _grx_v;
        _grx_v.expression = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction2(std::vector<StackEntry>* _grx_stack) {
        Conjunction* C = _grx_stack->back().payload.conjunction;
        _grx_stack->pop_back();
        Expression* v;
        {
         v = new Expression(C); 
        }
        StackEntryPayload _grx_v;
        _grx_v.expression = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction3(std::vector<StackEntry>* _grx_stack) {
        Expression* v;
        {
         v = new Expression(); 
        }
        StackEntryPayload _grx_v;
        _grx_v.expression = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction4(std::vector<StackEntry>* _grx_stack) {
        Match* M = _grx_stack->back().payload.match;
        _grx_stack->pop_back();
        Conjunction* C = _grx_stack->back().payload.conjunction;
        _grx_stack->pop_back();
        Conjunction* v;
        {
         v = C; v->add_child(M); 
        }
        StackEntryPayload _grx_v;
        _grx_v.conjunction = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction5(std::vector<StackEntry>* _grx_stack) {
        Match* M = _grx_stack->back().payload.match;
        _grx_stack->pop_back();
        Conjunction* v;
        {
         v = new Conjunction(M); 
        }
        StackEntryPayload _grx_v;
        _grx_v.conjunction = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction6(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Expression* E = _grx_stack->back().payload.expression;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        Group* v;
        {
         v = new Group(false, E); 
        }
        StackEntryPayload _grx_v;
        _grx_v.group = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction7(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Expression* E = _grx_stack->back().payload.expression;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        Group* v;
        {
         v = new Group(true, E); 
        }
        StackEntryPayload _grx_v;
        _grx_v.group = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction8(std::vector<StackEntry>* _grx_stack) {
        Quantifier Q = _grx_stack->back().payload.quantifier;
        _grx_stack->pop_back();
        MatchElement* ME = _grx_stack->back().payload.match_elem;
        _grx_stack->pop_back();
        Match* v;
        {
         v = new Match(ME, Q); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction9(std::vector<StackEntry>* _grx_stack) {
        MatchElement* ME = _grx_stack->back().payload.match_elem;
        _grx_stack->pop_back();
        Match* v;
        {
         v = new Match(ME); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction10(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Quantifier v;
        {
         v = Quantifier::Star; 
        }
        StackEntryPayload _grx_v;
        _grx_v.quantifier = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction11(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Quantifier v;
        {
         v = Quantifier::Plus; 
        }
        StackEntryPayload _grx_v;
        _grx_v.quantifier = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction12(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        Quantifier v;
        {
         v = Quantifier::QuestionMark; 
        }
        StackEntryPayload _grx_v;
        _grx_v.quantifier = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction13(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        MatchElement* v;
        {
         v = new DotMatchElement(); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match_elem = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction14(std::vector<StackEntry>* _grx_stack) {
        CharacterClass CC = _grx_stack->back().payload.character_class;
        _grx_stack->pop_back();
        MatchElement* v;
        {
         v = new CharacterClassMatchElement(CC); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match_elem = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction15(std::vector<StackEntry>* _grx_stack) {
        CharacterAlt* CA = _grx_stack->back().payload.character_alt;
        _grx_stack->pop_back();
        MatchElement* v;
        {
         v = new CharacterAltMatchElement(CA); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match_elem = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction16(std::vector<StackEntry>* _grx_stack) {
        char L = _grx_stack->back().payload.literal;
        _grx_stack->pop_back();
        MatchElement* v;
        {
         v = new LiteralMatchElement(L); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match_elem = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction17(std::vector<StackEntry>* _grx_stack) {
        Group* G = _grx_stack->back().payload.group;
        _grx_stack->pop_back();
        MatchElement* v;
        {
         v = new GroupMatchElement(G); 
        }
        StackEntryPayload _grx_v;
        _grx_v.match_elem = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction18(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::WordChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction19(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::NonWordChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction20(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::DigitChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction21(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::NonDigitChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction22(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::WhiteSpaceChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction23(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterClass v;
        {
         v = CharacterClass::NonWhiteSpaceChars; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_class = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction24(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::Normal, CS); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction25(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::Negated, CS); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction26(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::NormalIncludingClosingBracket, CS); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction27(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::NegatedIncludingClosingBracket, CS); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction28(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::NormalIncludingClosingBracket, nullptr); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction29(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        CharacterAlt* v;
        {
         v = new CharacterAlt(CharacterAltType::NegatedIncludingClosingBracket, nullptr); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_alt = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction30(std::vector<StackEntry>* _grx_stack) {
        CharacterRange* CR = _grx_stack->back().payload.character_range;
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        CharacterSet* v;
        {
         v = CS; v->add_range(CR); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction31(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        CharacterSet* v;
        {
         v = CS; v->add_range(new CharacterRange('^')); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction32(std::vector<StackEntry>* _grx_stack) {
        CharacterRange* CR = _grx_stack->back().payload.character_range;
        _grx_stack->pop_back();
        CharacterSet* v;
        {
         v = new CharacterSet(CR); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction33(std::vector<StackEntry>* _grx_stack) {
        CharacterClass CC = _grx_stack->back().payload.character_class;
        _grx_stack->pop_back();
        CharacterSet* CS = _grx_stack->back().payload.character_set;
        _grx_stack->pop_back();
        CharacterSet* v;
        {
         v = CS; v->add_character_class(CC); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction34(std::vector<StackEntry>* _grx_stack) {
        CharacterClass CC = _grx_stack->back().payload.character_class;
        _grx_stack->pop_back();
        CharacterSet* v;
        {
         v = new CharacterSet(CC); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction35(std::vector<StackEntry>* _grx_stack) {
        char UB = _grx_stack->back().payload.character_set_char;
        _grx_stack->pop_back();
        _grx_stack->pop_back();
        char LB = _grx_stack->back().payload.character_set_char;
        _grx_stack->pop_back();
        CharacterRange* v;
        {
         v = new CharacterRange(LB, UB); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_range = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction36(std::vector<StackEntry>* _grx_stack) {
        char C = _grx_stack->back().payload.character_set_char;
        _grx_stack->pop_back();
        CharacterRange* v;
        {
         v = new CharacterRange(C); 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_range = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction37(std::vector<StackEntry>* _grx_stack) {
        char C = _grx_stack->back().payload.CHARACTER;
        _grx_stack->pop_back();
        char v;
        {
         v = C; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction38(std::vector<StackEntry>* _grx_stack) {
        char SC = _grx_stack->back().payload.SPECIAL_CHARACTER;
        _grx_stack->pop_back();
        char v;
        {
         v = SC; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction39(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '|'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction40(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '['; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction41(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '.'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction42(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '+'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction43(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '('; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction44(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = ')'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction45(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '?'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction46(std::vector<StackEntry>* _grx_stack) {
        _grx_stack->pop_back();
        char v;
        {
         v = '*'; 
        }
        StackEntryPayload _grx_v;
        _grx_v.character_set_char = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction47(std::vector<StackEntry>* _grx_stack) {
        char C = _grx_stack->back().payload.CHARACTER;
        _grx_stack->pop_back();
        char v;
        {
         v = C; 
        }
        StackEntryPayload _grx_v;
        _grx_v.literal = v;
        return _grx_v;
    }
    static StackEntryPayload _reduction48(std::vector<StackEntry>* _grx_stack) {
        char SC = _grx_stack->back().payload.SPECIAL_CHARACTER;
        _grx_stack->pop_back();
        char v;
        {
         v = SC; 
        }
        StackEntryPayload _grx_v;
        _grx_v.literal = v;
        return _grx_v;
    }
    static constexpr StackEntryPayload (*reductions[])(std::vector<StackEntry>*) = {_reduction0, _reduction1, _reduction2, _reduction3, _reduction4, _reduction5, _reduction6, _reduction7, _reduction8, _reduction9, _reduction10, _reduction11, _reduction12, _reduction13, _reduction14, _reduction15, _reduction16, _reduction17, _reduction18, _reduction19, _reduction20, _reduction21, _reduction22, _reduction23, _reduction24, _reduction25, _reduction26, _reduction27, _reduction28, _reduction29, _reduction30, _reduction31, _reduction32, _reduction33, _reduction34, _reduction35, _reduction36, _reduction37, _reduction38, _reduction39, _reduction40, _reduction41, _reduction42, _reduction43, _reduction44, _reduction45, _reduction46, _reduction47, _reduction48};

    std::vector<StackEntry> stack;
    StackEntryPayload payload;
    bool payloadInitialized = false;
public:
    Parser() {
        stack.emplace_back();
    }
    void reset() {
        stack.clear();
        stack.emplace_back();
        payloadInitialized = false;
    }
    bool parse(int tokenId, StackEntryPayload tokenPayload) {
        while (true) {
            int action = actionTable[TERMINAL_COUNT * stack.back().previousState + tokenId];
            if (action == 0) {
                return false;
            }
            if (action == -1) {
                payload = stack.back().payload;
                payloadInitialized = true;
                return true;
            }
            if (action > 0) {
                stack.emplace_back(action - 1, tokenPayload);
                return true;
            }
            const int productionIndex = -action - 2;
            const StackEntryPayload reducedProduction = reductions[productionIndex](&stack);
            const StackEntry& newState = stack.back();
            const int nextState = gotoTable[newState.previousState * NON_TERMINAL_COUNT + productionLabels[productionIndex]];
            stack.emplace_back(nextState - 1, reducedProduction);
        }
    }
    [[nodiscard]] bool successfullyParsed() const {
        return payloadInitialized;
    }
    [[nodiscard]] StackEntryPayload getValue() const {
        return payload;
    }
};

#endif